### ISSUE TITLE
Can't  define Stockfish

### ISSUE THREAD

**Issue by Bingonemo123** [zhelyabuzhsky/stockfish#1]
when I write first two line of  usage code:
`from stockfish import Stockfish`
`stockfish = Stockfish()`
return error:
`'Stockfish' object has no attribute 'stockfish'`
Using python 3.5 ,Windows 10 .

**Comment by zhelyabuzhsky** [comment]
Thanks for your question. You should pass stockfish's path as argument of constructor.
For example:
```python
from stockfish import Stockfish
stockfish = Stockfish('C:\Program Files\Stockfish\stockfish.exe')
```
