### ISSUE TITLE
Option to get board visual from either side

### ISSUE THREAD

**Issue by johndoknjas** [zhelyabuzhsky/stockfish#103]
For the get_board_visual function, it might be useful to let the user get the board from Black's side, if they choose. E.g., a bool param could be added to the function, representing whether to get the board from white's side (user can get the board from Black's side by sending in False as the arg). This param should probably be optional and set to True by default, in order to not break existing code using the function.

Some code would have to be written to flip the board, since afaik Stockfish only returns it from White's side.

**Comment by kieferro** [comment]
I think that's a good idea.
If that would be helpful, I could implement that, unless you have already started writing code for it, or if you want to implement it yourself.

**Comment by johndoknjas** [comment]
@kieferro Sure, that would be helpful, thanks :) I haven't starting implementing it myself so no problems there.
