### ISSUE TITLE
Stockfish 15 Errors on Linux

### ISSUE THREAD

**Issue by Descent098** [zhelyabuzhsky/stockfish#117]
When trying to use any of the [official stockfish 15 linux binaries](https://stockfishchess.org/download/linux/) there is an error while parsing the version:

```python
Traceback (most recent call last):
  File "app.py", line 16, in <module>
    stockfish = Stockfish(path=stockfish_path, depth=18, parameters=parameters)
  File "/usr/local/lib/python3.8/site-packages/stockfish/models.py", line 57, in __init__
    self._stockfish_major_version: int = int(
ValueError: invalid literal for int() with base 10: '/lib/x86_64linuxgnu/libm'
```

Testing this again with the historical copy of [stockfish 14](https://www.dropbox.com/sh/75gzfgu7qo94pvh/AAAZLV-YmwZBDO_NEvaer87pa/Stockfish%2014?dl=0&subfolder_nav_tracking=1) from their archive repo it works correctly.

**Comment by johndoknjas** [comment]
Hi @Descent098, would you mind running the SF 15 and SF 14 binaries directly, and let me know the text that shows up  for you on the first line? It should start with "Stockfish 15/14 by the Stockfish developers..."

**Comment by Descent098** [comment]
@johndoknjas I am back in the office Thursday and will give it another shot!

**Comment by johndoknjas** [comment]
@Descent098 Sounds good. I tried running the SF 15 binary directly on linux and it didn't work, even though SF 14 ran fine. The current release of Stockfish seems to require a more recent version of glibc than what is shipped with Ubuntu, so it seems like a problem they would have to fix.

**Comment by Descent098** [comment]
@johndoknjas Yep, seems to be the issue 

![image](https://user-images.githubusercontent.com/22761705/201158502-67d0f973-5ada-415d-bba6-430a22c6f630.png)

I will file an issue with official stockfish. Thanks for your work on the project!
