### ISSUE TITLE
set_position accepts FEN string

### ISSUE THREAD

**Issue by charlesoblack** [zhelyabuzhsky/stockfish#12]
Maybe the set_position and set_fen_position methods could be conflated? or at least the input checked to see if it makes sense.

```python
sf = stockfish.Stockfish('path-to-sf')
sf.set_position('2k5/3b4/p3p3/1p1pPn2/1Pp3pB/P3K3/2P2P2/8 w - - 2 36')
sf.get_best_move() #e2e4
```

**Comment by zhelyabuzhsky** [comment]
I'm sorry, but it seems to me that at the moment this is unnecessary
