### ISSUE TITLE
Get best move from current position

### ISSUE THREAD

**Issue by Ugroon** [zhelyabuzhsky/stockfish#127]
How can I get best move from current position?

**Comment by kieferro** [comment]
This is sample code for finding the best move in a position:
```python
from stockfish import Stockfish

# Create Stockfish object. Use your own path to the binary files of the stockfish engine
stockfish = Stockfish(path="...")

# Set a position
stockfish.set_fen_position("rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2")

# Get the best move
print(stockfish.get_best_move())
```
If you need more information, you can have a look at the [README](https://github.com/zhelyabuzhsky/stockfish#readme). There is a list of all available functions.
