### ISSUE TITLE
get_evaluation() implemented wrong

### ISSUE THREAD

**Issue by RottenSchnitzel** [zhelyabuzhsky/stockfish#132]
When calling get_evaluation() I expect the command `eval` to be put into stockfish. Currently the skript just executes a bestmove search and then uses the score of stockfishs best move.

This feature makes sense but is very misleading since it is called "get_evaluation". Maybe name it "get_bestmove_score" and actually call `eval` for "get_evaluation".

Very quick fix would be to at least add a note in the Readme.

**Comment by kieferro** [comment]
This project is now maintained [here](https://github.com/py-stockfish/stockfish) (#130). Could you close this issue here and open it again on the fork? Thanks

**Comment by RottenSchnitzel** [comment]
sure!
