### ISSUE TITLE
Can you change GPL to a more permissive license?

### ISSUE THREAD

**Issue by YizhePKU** [zhelyabuzhsky/stockfish#18]
This library looks great, but I'm hesitant to publish my code with GPL, which I must if I use this library. Would you please release the library with a more permissive license like MIT?

**Comment by zhelyabuzhsky** [comment]
Good idea. I'll do it as soon as possible.

**Comment by zhelyabuzhsky** [comment]
It's [licensed](https://github.com/zhelyabuzhsky/stockfish/blob/master/LICENSE) with MIT License now
