### ISSUE TITLE
Change stockfish parameters

### ISSUE THREAD

**Issue by GabrieleMaurina** [zhelyabuzhsky/stockfish#27]
Hello, I would like to know how to change Stockfish parameters other than skill level.

I would like to change "Threads" and  "Minimum Thinking Time".

Also: am I suppose to wait between setting up the board position and asking for the best move? Or can I ask it straight away?

Thanks a lot

**Comment by zhelyabuzhsky** [comment]
Hi =)

> I would like to know how to change Stockfish parameters other than skill level

You can pass them into the constructor of Stockfish class:

```python
stockfish = Stockfish(parameters={"Threads": 2, "Minimum Thinking Time": 30})
```

> am I suppose to wait between setting up the board position and asking for the best move? Or can I ask it straight away?

You can ask for the best move in the next line of code:

```python
stockfish.set_position(["e2e4", "e7e6"])
stockfish.get_best_move()
```

**Comment by zhelyabuzhsky** [comment]
I improved [Initialize Stockfish class](https://github.com/zhelyabuzhsky/stockfish#initialize-stockfish-class) section in documentation

**Comment by GabrieleMaurina** [comment]
Thank you for the suggestion.

My code looks something like this:

`stockfish = Stockfish(parameters={"Threads": 8, "Minimum Thinking Time": 1000})`

I have 8 threads and I want it to think fo a second. However it doesn't seem to affect the answer time. I can change the value to whichever number and it still give's the move almost instantly.

**Comment by zhelyabuzhsky** [comment]
I passed your parameters directly into the stockfish and it also gives the move almost instantly 🤷🏼‍♂️

**Comment by 2kofawsome** [comment]
I believe that specifying a depth (as each get_best_move does) overrides the minimum thinking time. Minimum thinking is used for like "go wtime 6000 btime 6000".

**Comment by zhelyabuzhsky** [comment]
https://github.com/zhelyabuzhsky/stockfish/pull/30

**Comment by GabrieleMaurina** [comment]
I believe this can solve my specific use case perfectly. I haven't try it yet though. Can I expect that this will be updated to pypi soon?

Nevertheless it would be best if stockfish parameters worked as expected.

**Comment by zhelyabuzhsky** [comment]
>  Can I expect that this will be updated to pypi soon?

It's already on pypi =) https://pypi.org/project/stockfish/3.10.0/

**Comment by zhelyabuzhsky** [comment]
> Nevertheless it would be best if stockfish parameters worked as expected.

I completely agree...

**Comment by 2kofawsome** [comment]
Heres the specific line which makes it not work [here](https://github.com/official-stockfish/Stockfish/blob/15e190e9428b21fbfe29ce020c456077dc5fdd04/src/search.h#L94). The get_best_move() method uses "go depth" so its on the excluded list.

If you require stockfish to use a minimum time instead of a specific time (as in the get_best_move_time() method), I can likely add that method to this module.
