### ISSUE TITLE
No exception raised when fen position is wrong

### ISSUE THREAD

**Issue by GabrieleMaurina** [zhelyabuzhsky/stockfish#28]
Hi,
it's me again.

When I accidentally set a wrong fen position and ask for the best move, stockfish hangs forever without returning anything or throwing an exception.

Here is an example

```python
from stockfish import Stockfish

#Wrong fen because there are too many kings
wrong_fen = '3kk3/8/8/8/8/8/8/3KK3 w - - 0 0'

s = Stockfish()
print('stockfish created')

s.set_fen_position(wrong_fen)
print('board position set')

try:
    move = s.get_best_move()
    print('best move is {}'.format(move))
except Exception as e:
    print('getting the best move failed with {}'.format(e))
finally:
    print('the end')
```

The output is:
```
stockfish created
board position set
stockfish: /builddir/build/BUILD/stockfish-10/src/position.h:255: Square Position::square(Color) const [with PieceType Pt = KING]: Assertion `pieceCount[make_piece(c, Pt)] == 1' failed.
```

As you can see no exception was raised or caught. But even more problematic is that the call get_best_move doesn't return at all. This is an issue because when using it inside an application, it might get stuck there without you even knowing.

**Comment by zhelyabuzhsky** [comment]
Thank you. I'll fix it soon.

**Comment by zhelyabuzhsky** [comment]
I tried your example:

```python
wrong_fen = '3kk3/8/8/8/8/8/8/3KK3 w - - 0 0'
s = Stockfish()
print('stockfish created')

s.set_fen_position(wrong_fen)
print('board position set')
move = s.get_best_move()
print('best move is {}'.format(move))
```

Output:

```
stockfish created
board position set
best move is d1c1
```

> But even more problematic is that the call get_best_move doesn't return at all

I can't confirm it

**Comment by GabrieleMaurina** [comment]
I guess we got different behaviors because we are on different systems. I am on Fedora 32, using Stockfish 10 and Python 3.8.

Anyway, in your case you got a "best move" in return, but I think there should be some exception instead, because the board has 4 kings, hence it is an impossible situation.

**Comment by zhelyabuzhsky** [comment]
> Anyway, in your case you got a "best move" in return, but I think there should be some exception instead, because the board has 4 kings, hence it is an impossible position.

but stockfish engine returns best move, doesn't it?

**Comment by GabrieleMaurina** [comment]
In my case it doesn't return anything and it hangs forever.

If in your case it returned a move, I don't understand how that would be correct, since there is a forbidden position on the board.

**Comment by zhelyabuzhsky** [comment]
Is this test case correct?

https://github.com/zhelyabuzhsky/stockfish/pull/37

**Comment by GabrieleMaurina** [comment]
I admit I am no expert in chess engines.

However it seems inappropriate to me to expect a move like "d1e2" given a wrong board position. In my opinion, it would be more appropriate if an exception was raised when attempting to set a wrong position.

**Comment by zhelyabuzhsky** [comment]
> an exception was raised when attempting to set a wrong position

This package is not chess engine, it's only the wrapper for stockfish chess engine

If stockfish dont rise an excpetion for wrong position, I think we should not do it also.

**Comment by GabrieleMaurina** [comment]
I understand this is a wrapper. Chess engines generally communicate to the user through the UCI, hence they cannot raise exceptions. This wrapper communicates to its users through python, so it would be possible to raise an exception. I understand this is a design choice and you free to make your own decision.
