### ISSUE TITLE
getting position evaluation

### ISSUE THREAD

**Issue by saikrishna-1996** [zhelyabuzhsky/stockfish#3]
1) I could only see get_best_move(), but, how do we get the stockfish's evaluation? 
2) Do we have to close the stockfish after getting best move in every position? Because, the speed seems to be decreasing if I put get_best_move() in a loop

**Comment by zhelyabuzhsky** [comment]
Hello
Thanks for your questions
1. There is not function to get the stockfish evaluation yet. Your merge request is welcome =)
2. No, you can set several positions in succession and get hints with the best moves on them without closing the stockfish.

**Comment by saikrishna-1996** [comment]
python-chess has the option to get evaluations also. I wrote a Stockfish() class to simplify things: https://github.com/saikrishna-1996/deep_pepper_chess/blob/master/game/stockfish.py Would be nice if this can be integrated.
