### ISSUE TITLE
get_fen_position() doesn't work after set_position()

### ISSUE THREAD

**Issue by CharlesGraven** [zhelyabuzhsky/stockfish#31]
After running stockfish.set_position([VALID MOVES])
and then trying print(stockfish.get_fen_position())
you will only be returned the starting fen position, not where you expect after running set_position.

This is problematic since I'm trying to save FEN positions after setting the moves. Could someone see if this same issue is happening to them?

**Comment by zhelyabuzhsky** [comment]
Can't reproduce it ...

I added this test case:
```python
    def test_get_fen_position_after_some_moves(self, stockfish):
        stockfish.set_position(["e2e4", "e7e6"])
        assert (
            stockfish.get_fen_position()
            == "rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2" # it's not a start position
        )
```
