### ISSUE TITLE
Where to include stockfish = Stockfish("pathtostockfish")?

### ISSUE THREAD

**Issue by etfriedman** [zhelyabuzhsky/stockfish#32]
I'm getting this error:
`Traceback (most recent call last):
  File "C:\Users\etfri\anaconda3\envs\py38\lib\site-packages\stockfish\models.py", line 270, in __del__
    self.stockfish.kill()
AttributeError: 'Stockfish' object has no attribute 'stockfish'`

As you mentioned, I have installed the stockfish binaries to C:\Users\etfri\Desktop\stockfishlib,

but where should I include the stockfish = Stockfish("/Users/etfri/Desktop/stockfishlib")? inside the Stockfish class, before / after?

**Comment by CharlesGraven** [comment]
from stockfish import Stockfish

chessEngine = Stockfish("C:/Users/cjgra/Desktop/stockfish/stockfish-11win/Windows/stockfish_20011801_32bit.exe")

Mine looks like this. I noticed you don't have the .exe path so maybe that is your issue.

**Comment by etfriedman** [comment]
Thank you
