### ISSUE TITLE
"stockfish.info" is giving one Depth value and "stockfish.depth" is giving another value

### ISSUE THREAD

**Issue by karthik057** [zhelyabuzhsky/stockfish#38]
"stockfish.info" is giving one Depth value and "stockfish.depth" is giving another value, can anyone please tell which one is the correct value? and which one should i consider?
thank you

**Comment by zhelyabuzhsky** [comment]
Hello

As you see in [this test case](https://github.com/zhelyabuzhsky/stockfish/blob/master/tests/stockfish/test_models.py#L198), the values are the same. Please give me an example that reproduces the problem.

**Comment by karthik057** [comment]
> Hello
> 
> As you see in [this test case](https://github.com/zhelyabuzhsky/stockfish/blob/master/tests/stockfish/test_models.py#L198), the values are the same. Please give me an example that reproduces the problem.

ya actually i have used get_best_move_time() in my code so the depth command was overridden by the time limit i have put, thereby going to different depth, now i understand why and I have one another doubt if i use get_best_move() iam getting the move almost immediately its taking around 15ms(min think time-every  time) but how to make it flexible?  i thought by default stock fish decides the time taken to make a move and its depth depending open the situation in the game and time left in the game but there is no way to pass game time to stockfish &  if am using get_best_move() it is giving out the move instantly & if i use get_best_move_time() i directly overriding the stockfish flexibility..can you please tell me a way to attain the inherent flexible judgement of stockfish?
Thank you

**Comment by Pavocracy** [comment]
> can you please tell me a way to attain the inherent flexible judgement of stockfish? in order to balance strength along with time. Thank you

That would require adding the "wtime", "btime" and "ponder" options to this python wrapper. 

[you can see here how the c++ stockfish options work.](https://github.com/official-stockfish/Stockfish/blob/master/src/uci.cpp)

**Comment by zhelyabuzhsky** [comment]
Solved here https://github.com/zhelyabuzhsky/stockfish/pull/85
