### ISSUE TITLE
cannot import name 'Stockfish' from 'stockfish'

### ISSUE THREAD

**Issue by SURFLOU** [zhelyabuzhsky/stockfish#4]
while opening this python file:
```
from stockfish import Stockfish

stockfish = Stockfish('/Users/zhelyabuzhsky/Work/stockfish/stockfish-9-64')
```

get a following error: 

> ImportError: cannot import name 'Stockfish' from 'stockfish'

**Comment by SURFLOU** [comment]
nvm fixed

**Comment by jonathanmorlen** [comment]
Can you explain your fix? I am getting the same error
