### ISSUE TITLE
Get evaluation is too slow

### ISSUE THREAD

**Issue by IrenvanderBeekPXL** [zhelyabuzhsky/stockfish#44]
Hello

I am making a chess analyzing program, and to test it, I wanted to see what it thinks of the Sicillian Defense opening (e4, c5). For the first move, it tells me e4 is the best move, which is a really strong move. For c5, it doesn't think it's the best move (thats ok), so it thinks for 5 hours to evaluate the position at depth 25 with 4 threads. (btw, it needs longer than 5 hours to evaluate the position, while Lichess does it within 10 minutes if it analyzes locally.) Can you please explain why this happens and fix it for me? (I need to do it twice for 1 move and can't debug my program if it's wrong)

Thanks

**Comment by zhelyabuzhsky** [comment]
Hello

Which version of stockfish are you using?

**Comment by IrenvanderBeekPXL** [comment]
I am using Stockfish 12 with AVX2 extention

**Comment by zhelyabuzhsky** [comment]
Thank you for your bug report!

I fixed it in version 3.12.1

Please, check it now :)

**Comment by IrenvanderBeekPXL** [comment]
I will try it soon. Thanks
