### ISSUE TITLE
evaluation does not work in SF 12

### ISSUE THREAD

**Issue by Laterunner** [zhelyabuzhsky/stockfish#47]
Hi Ilya, 
I checked this several times with different settings, **"stockfish.get_evaluation()"** does not work in stockfish 12.
It works well in stockfish 8. Maybe this is a Stockfish 12 specific problem ??

here is a debug:
{'Write Debug Log': 'false', 'Contempt': 0, 'Min Split Depth': 0, 'Threads': 2, 'Ponder': 'false', 'Hash': 16, 'MultiPV': 1, 'Skill Level': 20, 'Move Overhead': 30, 'Minimum Thinking Time': 20, 'Slow Mover': 80, 'UCI_Chess960': 'false'}
^CTraceback (most recent call last):
  File "/home/nnn/Desktop/pypro/stockfishTest.py", line 35, in <module>
    print(stockfish.get_evaluation()['type'])
  File "/home/nnn/tf2/lib/python3.6/site-packages/stockfish/models.py", line 246, in get_evaluation
    text = self._read_line()
  File "/home/nnn/tf2/lib/python3.6/site-packages/stockfish/models.py", line 73, in _read_line
    return self.stockfish.stdout.readline().strip()

Kind regards

Marius

**Comment by zhelyabuzhsky** [comment]
duplicate #44

**Comment by zhelyabuzhsky** [comment]
Hello

Thank you for your bug report!

I fixed it in version 3.12.1

Please, check it now :)
