### ISSUE TITLE
Import resolves to Its containing file/cannot find reference 'Stockfish' in 'stockfish.py'

### ISSUE THREAD

**Issue by jonathanmorlen** [zhelyabuzhsky/stockfish#51]
Trying out the stockfish wrapper with some simple code

    from stockfish import Stockfish

    stockfish = Stockfish('D:/Programming/Python/test/stockfish.exe')

When I hover over 'stockfish' in the import statement, Pycharm tells me "Import resolves to its containing file"
When I hover over 'Stockfish' in the import statement, Pycharm tells me "Cannot find reference 'Stockfish' in 'stockfish.py'"

My stockfish executable is in the same folder as the .py file
When run it gives me this error:

    Traceback (most recent call last):
      File "D:/Programming/Python/test/stockfish.py", line 1, in <module>
        from stockfish import Stockfish
      File "D:\Programming\Python\test\stockfish.py", line 1, in <module>
        from stockfish import Stockfish
    ImportError: cannot import name 'Stockfish' from partially initialized module 'stockfish' (most likely due to a circular import) 
    (D:\Programming\Python\test\stockfish.py)

Python 3.8
Stockfish 12
Windows 10

**Comment by zhelyabuzhsky** [comment]
Hello )

I have [added](https://github.com/zhelyabuzhsky/stockfish/blob/master/.github/workflows/build.yml#L58) Windows to GitHub actions build.

As you see, it's "green".

**Comment by IrenvanderBeekPXL** [comment]
Which Python interpreter do you use in Pycharm? (anaconda won't work and does not support pip)

**Comment by zhelyabuzhsky** [comment]
I use MacOS, not Windows
