### ISSUE TITLE
freezes when given certain fen inputs

### ISSUE THREAD

**Issue by frederikme** [zhelyabuzhsky/stockfish#53]
Hi,

I have an instance of Stockfish working perfectly, however when some fen strings are given as input, there is no return value to the `stockfish.get_best_move()` and it just keeps thinking infinitely without returning anything. Can you try running the code below please?

As you run it, you can see the visual board that shows and it surely exists (since it's a real time scenario of a game).
But the move won't show and the program will keep running.
```
from stockfish import Stockfish


params = {
            "Threads": 1,
            "Ponder": "true",
            "Skill Level": 20
        }

stockfish = Stockfish(path="stockfish12/bin/stockfish", depth=6, parameters=params)

stockfish.set_fen_position('4r3/pbk4p/1p1n4/2p5/3p4/7P/PPP2Pr1/RN1R2K1 b KQkq - 0 1')

print(stockfish.get_board_visual())
print(stockfish.get_best_move())
``` 

Thanks in advance,

Fred

**Comment by VivekThazhathattil** [comment]
![image](https://user-images.githubusercontent.com/63693789/119985410-3c4a1680-bfe0-11eb-902c-7e0c3e36517d.png)
From the FEN string, its black's turn to move, but white king is already in check. So the FEN string is invalid.
