### ISSUE TITLE
Can't unambiguously make castling moves  in custom Chess960 position

### ISSUE THREAD

**Issue by ekorchmar** [zhelyabuzhsky/stockfish#65]
```
import stockfish

bot = stockfish.Stockfish('stockfish')
bot.set_fen_position('4rkr1/4p1p1/8/8/8/8/8/5K1R w H - 0 100')  # Chess 960, white has mate in 1 in castling
print(bot.get_best_move())  # f1g1 -- castling or normal king move?
```

In this custom position, white has mate in 1 if castling is performed. Engine recognises this and attempts to castle, but resulting output can mean either castling, or normal move.

**Comment by johndoknjas** [comment]
Hi,

Even though your fen is correct for Chess960 (i.e., the 'H' field), SF is still assuming the game is standard chess. The f1g1 move it gives means Kg1. In Chess960, Kg1 would still have the notation f1g1, while castling would be f1h1.

If you replace

```
bot = stockfish.Stockfish('stockfish')
```
with
```
bot = stockfish.Stockfish(path='stockfish', parameters={"UCI_Chess960": "true"})
```
then SF should give castling (f1h1) as the best move.
