### ISSUE TITLE
Exception when creating stockfish instance with newest version 14.1

### ISSUE THREAD

**Issue by stefankirchfeld** [zhelyabuzhsky/stockfish#70]
Since yesterday, stockfish 14.1 is online. With that version, calling the constructor, I get:

File "/usr/local/lib/python3.10/site-packages/stockfish/models.py", line 39, in __init__
    self._stockfish_major_version: int = int(self._read_line().split(" ")[1])
ValueError: invalid literal for int() with base 10: '14.1'

**Comment by Pavocracy** [comment]
I can confirm i also have this issue.

You can fix this by opening models.py and changing line 39 to be "self._stockfish_major_version: float = float(self._read_line().split(" ")[1])"

I do not know the implications of this change for the whole class, but it will fix this error.

**Comment by stefankirchfeld** [comment]
I just removed the complete “get major version” API….didn’t need it

**Comment by zhelyabuzhsky** [comment]
Fixed in #71
