### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by A-Gad** [zhelyabuzhsky/stockfish#87]
i dont get any output when i use any of the  functions , and i dont get an error either 
i don t know what i am doing wrong, please help if u can

**Comment by A-Gad** [comment]
> @A-Gad Hi, could you please give an example of how your code uses one of the functions?

@johndoknjas  thanks for answering here is my code :
from stockfish import Stockfish
stockfish = Stockfish(path='stockfish_14.1_win_x64_avx2.exe')
stockfish.set_fen_position("rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2")
stockfish.get_best_move()

**Comment by johndoknjas** [comment]
@A-Gad Thanks for the code. The get_best_move function doesn't print anything, but will instead return the best move as a string (or if there are no legal moves in the position, the None object is returned).
Something like this should do what you want:
```
best_move = stockfish.get_best_move()
print(best_move)
```

**Comment by A-Gad** [comment]
@johndoknjas  thank you so much for your help
